services:
  web_app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/:Z
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - postgres
    container_name: my_django
  
  postgres:
    image: postgres:14.3
    volumes: 
      - ./postgres/pg_data:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env
    container_name: my_postgres

volumes:
  pg_data:
