services:
  web_prod:
    image: django_prod:v2
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.prod
    container_name: my_django
    depends_on:
      - postgres_prod

  postgres_prod:
    image: postgres:14.3
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env.prod
    container_name: my_postgres
